# default config

# data paths
data_path = "/home/muninn/scratch/kaufmanl/CAP/results/tahoe/pseudobulks/filtered_pseudobulks_alpha_10000.jld2"
data_format = "tahoe"
modeltype = "rtf"
sorted_gene_path = ""

# single-cell data paths
data_dir = "/home/muninn/scratch/kaufmanl/CAP/data/Tahoe-100M/data"
meta_dir = "/home/muninn/scratch/kaufmanl/CAP/data/Tahoe-100M/metadata"
coding_gene_path = "/home/muninn/scratch/kaufmanl/CAP/data/protein-coding_gene.txt"

# constant params
batch_size = 128
n_epochs  = 0
embed_dim = 128
hidden_dim = 128
n_heads = 2
n_layers = 2
n_hvg = 1024 # bulk sequence length
top_k = 1024 # single-cell sequence length
n_eval_shards = 10
subset_ratio = 1.0
max_steps = 160000 # pre-train

# variable params
lr = 0.0005
drop_prob = 0.1
mask_ratio = 0.15
ema_decay = 0.9

# finetune specifics
model_dir = ""
mode = ""
task = "mlm"
level = "lvl2"
max_ft_steps = 0
label_path = ""

# lvl3 references/targets
source_cell = "MCF7"
target_cell = "PC3"
target_gene = "IGFBP3"

# misc
wandb_mode = "online"
additional_notes = ""
