# default config

# data paths
data_path = ""
data_format = "tahoe"
modeltype = "rtf"
sorted_gene_path = ""

# single-cell data paths
data_dir = ""
meta_dir = ""
coding_gene_path = ""

# constant params
batch_size = 128
n_epochs  = 0
embed_dim = 128
hidden_dim = 128
n_heads = 2
n_layers = 2
n_hvg = 1024 # for ETF
top_k = 1024 # for RTF
hvg_path = "data/hvg_indices.jld2" # pre-computed HVG indices for SC-ETF (30-shard, 846k cells)
n_eval_shards = 10
subset_shards = 0
subset_ratio = 1.0
max_steps = 160000 # pre-train

# variable params
lr = 0.0005
drop_prob = 0.1
mask_ratio = 0.15
ema_decay = 0.9

# finetune specifics
model_dir = ""
mode = ""
task = "mlm"
level = "lvl2"
max_ft_steps = 0
label_path = ""

# lvl3 references/targets
source_cell = "MCF7"
target_cell = "PC3"
# target_gene = "IGFBP3"  # replaced by PCA-based prediction
dose = ""  # dose filter: "5.0" for Tahoe, "10" for LINCS; empty = no filter

# misc
wandb_mode = "online"
additional_notes = ""
