# [dataset.task.modeltype] to the pre-trained model to use for fine-tuning

# LINCS

[lincs.mlm]
rtf = "results/lincs/pretrain/mlm/rtf/2026-08-03_01-36/best"
etf = "results/lincs/pretrain/mlm/etf/2026-08-03_01-36/best"

[lincs.lrecon]
rtf = ""
etf = ""

[lincs.erecon]
rtf = ""
etf = ""

# tahoe pseudobulk

[tahoe_pb.mlm]
rtf = "results/tahoe/pb/pretrain/mlm/rtf/2026-08-21_22-50/best"
etf = "results/tahoe/pb/pretrain/mlm/etf/2026-08-27_11-51/best" # 160k steps, pearson=0.769, spearman=0.745, best_val_loss=5.450

[tahoe_pb.lrecon]
rtf = "results/tahoe/pb/pretrain/lrecon/rtf/2026-08-22_17-36/best"
etf = "results/tahoe/pb/pretrain/lrecon/etf/2026-08-27_11-51/best" # 160k steps, best_val_loss=0.0064 (newer script)

[tahoe_pb.erecon]
rtf = "results/tahoe/pb/pretrain/erecon/rtf/2026-08-18_13-15/best"
etf = "results/tahoe/pb/pretrain/erecon/etf/2026-08-27_11-51/best" # 160k steps, pearson=0.978, spearman=0.973, best_val_loss=0.029

# tahoe single-cell

[tahoe_sc.mlm]
rtf = "results/tahoe/sc/pretrain/mlm/rtf/2026-08-24_11-28/best"
etf = "results/tahoe/sc/pretrain/mlm/etf/2026-08-27_03-27/best"

[tahoe_sc.lrecon]
rtf = "results/tahoe/sc/pretrain/lrecon/rtf/2026-08-23_23-39/best"
etf = "results/tahoe/sc/pretrain/lrecon/etf/2026-08-23_23-48/best"

[tahoe_sc.erecon]
rtf = "results/tahoe/sc/pretrain/erecon/rtf/2026-08-23_23-57/best"
etf = "results/tahoe/sc/pretrain/erecon/etf/2026-08-24_00-04/best"
