# [dataset.task.modeltype] to the pre-trained model to use for fine-tuning

# LINCS

[lincs.mlm]
rtf = "results/lincs/pretrain/mlm/rtf/2026-08-03_01-36/best"
etf = "results/lincs/pretrain/mlm/etf/2026-08-03_01-36/best"

[lincs.lrecon]
rtf = ""
etf = ""

[lincs.erecon]
rtf = ""
etf = ""

# tahoe pseudobulk

[tahoe_pb.mlm]
rtf = "results/tahoe/pb/pretrain/mlm/rtf/2026-08-21_22-50/best"
etf = "results/tahoe/pb/pretrain/mlm/etf/2026-08-02_16-54/best" # NOT COMPLETE

[tahoe_pb.lrecon]
rtf = "results/tahoe/pb/pretrain/lrecon/rtf/2026-08-22_17-36/best"
etf = "results/tahoe/pb/pretrain/lrecon/etf/2026-08-17_22-12/best"

[tahoe_pb.erecon]
rtf = "results/tahoe/pb/pretrain/lrecon/rtf/2026-08-18_13-15/best"
etf = "results/tahoe/pb/pretrain/erecon/etf/2026-08-22_07-50/best"

# tahoe single-cell

# [tahoe_sc.mlm]
# rtf = "results/tahoe/sc/pretrain/mlm/rtf/2026-08-24_11-28/best/"
# etf = ""

# [tahoe_sc.lrecon]
# rtf = ""
# etf = ""

# [tahoe_sc.erecon]
# rtf = ""
# etf = ""
